// 51 Regulation lore items — SVG images in images/items/<id>.svg
// Fallback to emoji if image fails to load
const ITEMS = [
  { id: 'slop_clock',      name: '1001 Slop O\'Clock Clocks',     emoji: '🕐', color: '#4a9fd4', hint: 'Andrew ordered 1001 clocks as a prank on Geoff' },
  { id: 'alabama_poutine', name: 'Alabama Poutine',                emoji: '🍟', color: '#c0392b', hint: 'Fries with... Andrew\'s biggest laugh on the show' },
  { id: 'banana_shaft',    name: 'The Banana Shaft',               emoji: '🍌', color: '#f1c40f', hint: 'Coring out a banana to add chocolate or caramel' },
  { id: 'borzoi',          name: 'Borzoi',                         emoji: '🐕', color: '#d4a574', hint: 'The longest of dogs' },
  { id: 'bovril',          name: 'Bovril',                         emoji: '☕', color: '#8B4513', hint: 'Beefy tea. Fed an army. Makes a hearty cuppa.' },
  { id: 'bread_tag',       name: 'The Bread Tag',                  emoji: '🏷️', color: '#95a5a6', hint: 'Unbreakable steel clip. Will not break. Will not bend. Has a magnet.' },
  { id: 'choco_taco',      name: 'Choco Taco',                     emoji: '🍦', color: '#a0522d', hint: 'Discontinued Klondike ice cream. Gone too soon.' },
  { id: 'colin_caterpillar', name: 'Colin the Caterpillar',        emoji: '🐛', color: '#27ae60', hint: 'British chocolate roll cake from Marks & Spencer' },
  { id: 'cookie_puss',     name: 'Cookie Puss',                    emoji: '🎂', color: '#e74c3c', hint: 'Carvel ice cream cake character from the 1970s' },
  { id: 'cucumbers',       name: 'The Cucumbers',                  emoji: '🥒', color: '#2ecc71', hint: 'Andrew vs Gavin cucumber war — he will get them in' },
  { id: 'desk_waffles',    name: 'Desk Waffles',                   emoji: '🧇', color: '#e67e22', hint: 'Waffles cooked at a desk. As you do.' },
  { id: 'dino_nuggets',    name: 'Dino Nuggets',                   emoji: '🦕', color: '#f39c12', hint: 'Dinosaur-shaped chicken nuggets' },
  { id: 'doom_loom',       name: 'Doom of the Loom',               emoji: '🍹', color: '#8e44ad', hint: '$100 of fruit blended into one horrifying drink' },
  { id: 'frazzles',        name: 'Frazzles',                       emoji: '🥓', color: '#c0392b', hint: 'Bacon-flavoured British crisps' },
  { id: 'frubes',          name: 'Frubes',                         emoji: '🥛', color: '#ff69b4', hint: 'British gogurts. Gavin got bullied with them on Fridays.' },
  { id: 'fudgie_whale',    name: 'Fudgie the Whale',               emoji: '🐋', color: '#1a6b8a', hint: 'Carvel ice cream cake whale' },
  { id: 'fruit_gloves',    name: 'Fruit Gloves',                   emoji: '🍇', color: '#6c3483', hint: 'Geoff\'s grand plan to create fruit gloves' },
  { id: 'golden_gurp',     name: 'The Golden Gurp',                emoji: '🏆', color: '#ffd700', hint: '1-in-10 gold Gurpler, came with exclusive recording' },
  { id: 'gurpler_max',     name: 'Gurpler Max',                    emoji: '🚧', color: '#ff6600', hint: 'Giant construction/traffic management cones' },
  { id: 'ham_fan',         name: 'Ham Fan',                        emoji: '🍖', color: '#e8735a', hint: 'The license plate that launched the Ham Zone' },
  { id: 'honey_monster',   name: 'Honey Monster',                  emoji: '👾', color: '#f1c40f', hint: 'British Sugar Puffs/Honey Monster Puffs mascot' },
  { id: 'humpty_cannon',   name: 'Humpty Dumpty Cannon',           emoji: '💣', color: '#7f8c8d', hint: 'Royalist cannon on the walls of Colchester' },
  { id: 'icing_icepack',   name: 'Icing Ice Pack',                 emoji: '🧊', color: '#74b9ff', hint: 'Andrew used gingerbread icing as an ice pack whenever he got too hot' },
  { id: 'nugget_buddies',  name: 'Kerwin Frost Nugget Buddies',    emoji: '🍗', color: '#f39c12', hint: 'Adult happy meal collectibles Andrew went all in on' },
  { id: 'lil_gurp',        name: 'Lil Gurp',                       emoji: '🔩', color: '#bdc3c7', hint: 'A thimble' },
  { id: 'mexican_pizza',   name: 'Mexican Pizza',                  emoji: '🍕', color: '#e74c3c', hint: 'Removed Taco Bell menu item. Mourned deeply.' },
  { id: 'mini_fridge',     name: 'Mini Fridge Mic Stand',          emoji: '❄️', color: '#ecf0f1', hint: 'A thing that is NOT a mic stand, used as a mic stand' },
  { id: 'monster_munch',   name: 'Monster Munch',                  emoji: '👹', color: '#e74c3c', hint: 'British pickled onion baked corn snack' },
  { id: 'nanaimo_bar',     name: 'The Nanaimo Bar',                emoji: '🍫', color: '#4a2c2a', hint: 'Canadian layered dessert: chocolate, custard, coconut' },
  { id: 'nose_flaps',      name: 'Nose Flaps',                     emoji: '👃', color: '#ffab91', hint: 'Geoff has closeable nose flaps — tested and confirmed' },
  { id: 'owl_owl',         name: 'Owl Owl',                        emoji: '🦉', color: '#8B7355', hint: 'Henry the dog\'s owl toy' },
  { id: 'p_ake',           name: 'The P-ake',                      emoji: '🥧', color: '#deb887', hint: 'A cake in a pie. Andrew tur-duck-en\'d dessert.' },
  { id: 'pillow_mountain', name: 'Pillow Mountain',                emoji: '😴', color: '#b0c4de', hint: '2 body pillows + 6 regulation pillows. Andrew\'s sleep setup.' },
  { id: 'poffle',          name: 'Poffle',                         emoji: '🥞', color: '#f4a460', hint: 'Pancake mix cooked in a waffle maker' },
  { id: 'porta_potty',     name: 'The Pink Porta Potty',           emoji: '🚽', color: '#ff69b4', hint: 'Andrew gifted Geoff a pink porta potty while bathrooms were out' },
  { id: 'potato_smiles',   name: 'Potato Smiles',                  emoji: '🥔', color: '#f0c040', hint: 'Smiley face frozen potato snacks. Geoff had never had one.' },
  { id: 'puss_puss',       name: 'Puss Puss',                      emoji: '🐙', color: '#e91e8c', hint: 'Henry the dog\'s octopus toy' },
  { id: 'ratyboy',         name: 'Ratyboy',                        emoji: '🐀', color: '#696969', hint: 'Eric hates him. Andrew owns the media and merch rights.' },
  { id: 'reliant_robin',   name: 'Reliant Robin',                  emoji: '🚗', color: '#ff7f50', hint: 'If Gavin was a car — three-wheeled British icon' },
  { id: 'shit_shades',     name: 'Shit Shades',                    emoji: '🕶️', color: '#b8860b', hint: 'Sunglasses for pooping. Solve a problem you didn\'t know you had.' },
  { id: 'sleep_spaghetti', name: 'Sleep Spaghetti',                emoji: '🍝', color: '#ff6347', hint: 'Andrew\'s invention: pool noodles and socks for sleeping' },
  { id: 'smee',            name: 'Smee',                           emoji: '🐱', color: '#ffa500', hint: 'Gavin\'s cat' },
  { id: 'street_sharks',   name: 'Street Sharks',                  emoji: '🦈', color: '#4169e1', hint: 'Vin Diesel sold them' },
  { id: 'surstromming',    name: 'Surstromming',                   emoji: '🐟', color: '#90ee90', hint: 'Stinky fish. Used to test Geoff\'s nose flaps in the porta potty.' },
  { id: 'swan_attack',     name: 'Swan Attack',                    emoji: '🦢', color: '#f0f0f0', hint: 'Austin\'s famous aggressive swan attacked Geoff, Terminator 2 style' },
  { id: 'transform_snack', name: 'Transform-a-Snack',              emoji: '🚙', color: '#e74c3c', hint: 'British baked snack pieces that assemble into a 5-piece car' },
  { id: 'whoop_scoops',    name: 'The Whoop Scoops',               emoji: '🍨', color: '#ffb6c1', hint: 'Gavin\'s creation: hot hands repurposed as ice cream scoopers' },
  { id: 'wrist_pocket',    name: 'Wrist Pocket',                   emoji: '👜', color: '#9370db', hint: 'It\'s a pocket, but it\'s on your wrist' },
  { id: 'zine',            name: 'Zine (Not a Hat)',               emoji: '🎩', color: '#2f4f4f', hint: 'Certainly not a hat' },
  { id: 'thumb_sticks',    name: 'Thumb Sticks',                   emoji: '🕹️', color: '#1abc9c', hint: 'Progressively longer Xbox thumbsticks, one inch per win' },
  { id: 'purple_nightmare',name: 'Purple Nightmare',               emoji: '🫐', color: '#7b2d8b', hint: 'Geoff\'s story of a 20oz purple smoothie exploding on the floor' },
];
